### ISSUE TITLE
自動デプロイした時、起動しない

### ISSUE THREAD

**Issue by masutaka** [masutaka/masutaka-29hours#5]

**Comment by masutaka** [comment]
logrotate も疑ったが、時間的にデプロイの時っぽい

**Comment by masutaka** [comment]
Mackerel の監視に追加し、気づけるようにはなった。
https://github.com/masutaka/server-masutaka.net/pull/170

**Comment by masutaka** [comment]
昨日の 22:18:03 に落ちてた。突然死もあるんだ。
やはり superviser 入れたほうが良さそう。

```
/home/masutaka/.rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:129:in `sysread': end of file reached (EOFError)
        from /home/masutaka/.rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:129:in `readpartial'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:21:in `stream'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:118:in `request'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:91:in `user'
        from /opt/masutaka-29hours/releases/20150829060219/29hours/lib/twenty_nine_hours.rb:72:in `start'
        from /opt/masutaka-29hours/releases/20150829060219/29hours/lib/twenty_nine_hours.rb:39:in `watch'
        from 29hours.rb:17:in `<main>'
```

Mackerel の監視で気づいて、1:44:01 に `$ cap prod twenty_nine_hours:start` で手動復帰した。

![alert__masutaka_net_ _masutaka-net](https://cloud.githubusercontent.com/assets/170014/9697600/7f9eeda0-53cd-11e5-98bf-14f0060537b7.png)

**Comment by masutaka** [comment]
> やはり superviser 入れたほうが良さそう。

rbenv 使っていると supervisor は面倒そうなのと対症療法な気がするので、導入しない。
突然死は頻繁に起きるので、 #8 立てた。

この件はたまたま突然死とタイミングがあっただけかもしれないので、再現しなければクローズする。

**Comment by masutaka** [comment]
突然死が原因だったみたい。 #8 で解決した。
