### ISSUE TITLE
突然死する

### ISSUE THREAD

**Issue by masutaka** [masutaka/masutaka-29hours#8]
#7 で様子を見ることに。

**Comment by masutaka** [comment]
これで突然死が直ったら、 https://github.com/june29/29hours に PR 出すかも。
[Twitter gem でも話に出ていて](https://github.com/sferik/twitter/issues/535#issuecomment-35912653)、 https://github.com/sferik/twitter/issues/535 が [v6 のマイルストーン](https://github.com/sferik/twitter/milestones/v6)に上がっている。

**Comment by masutaka** [comment]
突然死直ったっぽい！

```
EOFError occured. Retry.
You are following 809 users.
```

**Comment by masutaka** [comment]
https://github.com/june29/29hours/pull/9 出したので、ひとまずクローズ。

**Comment by masutaka** [comment]
こんなパターンもあった。

```
EOFError occured. Retry.
/opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:16:in `initialize': Connection timed out - connect(2) for "199.59.148.241" port 443 (Errno::ETIMEDOUT)
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:16:in `new'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:16:in `stream'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:118:in `request'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:91:in `user'
        from /opt/masutaka-29hours/releases/20151011031825/29hours/lib/twenty_nine_hours.rb:72:in `start'
        from /opt/masutaka-29hours/releases/20151011031825/29hours/lib/twenty_nine_hours.rb:39:in `watch'
        from 29hours.rb:17:in `<main>'
```

**Comment by masutaka** [comment]
起動直後にまた落ちてた

```
TwentyNineHours:
  Matchers:
    KeywordsMatcher
  Notifiers:
    PushoverNotifier
  Linker:
    TwitterLinker

/opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete': Twitter::Error::ServiceUnavailable
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/response.rb:16:in `<<'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/response.rb:16:in `<<'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:22:in `stream'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:118:in `request'
        from /opt/masutaka-29hours/shared/29hours/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:91:in `user'
        from /opt/masutaka-29hours/releases/20151011031825/29hours/lib/twenty_nine_hours.rb:72:in `start'
        from /opt/masutaka-29hours/releases/20151011031825/29hours/lib/twenty_nine_hours.rb:39:in `watch'
        from 29hours.rb:17:in `<main>'
```

https://dev.twitter.com/overview/status によると、stream.twitter.com が Service disruption だった。
